cloudflare/next-on-pages

README.md
package.json
src/index.ts
templates/_worker.js/index.ts

Next.js 12 should continue to work, Next.js 13 now works, including the new [experimental `app` directory](https://beta.nextjs.org/docs/routing/fundamentals#the-app-directory).
Check out the README.md for an updated guide on creating a new Next.js 13 app!
Fixes #9

Next.js 13

---

README.md

The diff for the Next 13 `appDir` config doesn't highlight properly because of the indentation of the `+`.
| **Before:** | **After:**|
|------------|-------|
|  <img src="https://user-images.githubusercontent.com/73045936/203484001-71be88c2-4494-4c46-aaa3-05a466adb697.png" width="400"> | <img src="https://user-images.githubusercontent.com/73045936/203484055-bfba74a1-2dbd-4d6d-a889-fc2fc5652938.png" width="400"> |
_P.S. Thanks for creating this awesome tool! Just something super minor I found._

[Docs] Update README 'appDir' config diff

---

.changeset/young-coins-appear.md
templates/_worker.js/index.ts

in the _worker.js template take the provided env and spread its values into the global process.env so that bindings can be accessed in the Next.js application

spread env into process.env

---

.changeset/perfect-pens-breathe.md
src/index.ts

The step executing the actual build defaults to `npx`. The redundant Vercel CLI installation can be removed.
This automatically means that `pnpm` is now supported without fuss (package managers are recognized correctly and automatically) and slightly cleaner.
The main point it Vercel CLI only needs the config files to be in place, and that's what the code change does.
Closes #17
Closes #6

fix: remove vercel installation

---

.changeset/smooth-nails-smash.md
src/index.ts

Minor change to support middleware in `src` directory: https://nextjs.org/docs/advanced-features/src-directory
Otherwise the build is failing with:
```
ERROR: Could not map all functions to an entry in the manifest
```

add support for middleware in src dir

---

.changeset/twenty-spoons-search.md
package-lock.json
package.json
src/index.ts

- Fix which property is checked for `webpackChunk_N_E`
- Use regex to hack around a bug caused by our webpack minification. It doesn't appear to cause issues.
- Set esbuild's `minify` option to be enabled when the user uses `--experimental-minify`
Build is 3289854 bytes
- change (regular): -19566933 bytes.
- change (esbuild): -12028637 bytes.
- change (experim): -2272043 bytes.
- change (exp+esb): +0 bytes.
The primary reason minification was failing was due to checking the wrong property for `webpackChunk_N_E`. This was actually stored under `name` instead of `value`. Below is an example of the property object:
```
Node3 {
type: 'Identifier',
start: 57372,
end: 57388,
name: 'webpackChunk_N_E'
}
```
I did actually end up coming across a bug that only occurs if you use …

fix: minification

---

.changeset/forty-geese-reply.md
src/index.ts

The Cloudflare workers runtime does not implement certain properties, for instance `mode` and `credentials`. When [generating](https://github.com/vercel/next.js/blob/canary/packages/next/src/compiled/react/cjs/react.shared-subset.development.js#L191) a cache key for request deduping, the React Fetch 'monkey-patch' implementation tries to read some of these properties.
Therefore, the simple solution is to replace these specific properties with `null` when we build the _worker.js script as they would have no effect on the cache keys anyway.
https://github.com/cloudflare/workerd/blob/main/src/workerd/api/http.h#L518
https://github.com/cloudflare/miniflare/blob/master/packages/core/src/standards/http.ts#L501
fixes #36

fix: external fetch requests

---

.changeset/ninety-queens-pump.md
src/index.ts
src/utils/index.ts
src/utils/paths.ts
tests/utils.test.ts

On Windows, the file paths may use `\\` instead of `/`.
This would result in the error `Could not map all functions to an entry in the manifest.` being thrown.
When we are running through the middleware manifest entries and checking that our function entries exist in it, we are comparing an entry with `/` in it to our path with `\`  in it.
This change replaces the `\\` with `/` so they are in the same format as the middleware manifest when adding to the functions map.

fix: windows file paths not matching middleware manifest

---

.changeset/wild-eyes-wink.md
src/index.ts
templates/_worker.js/index.ts

The [basepath](https://nextjs.org/docs/api-reference/next.config.js/basepath) feature in Next.js allows applications to be hosted specific paths on the same domain like the following:
example.com/user/account <-- Next.js App 1
example.com/store/checkout <-- Next.js App 2
---
Currently `@cloudflare/next-on-pages` errors when using the basepath option, this PR aims at adding support by reading the basePath value from the build output, `.next/routes-manifest.json`, and then inlines the value into the Worker. 
Upon receiving a request, the worker will strip the `basePath` value from the pathname, and then run the matching logic with the stripped pathname. This appears to play nicely with everything else inside of Next's `base-server#handleRequest`, though I'm happy to move things around if …

Implement support for `next.config#basePath`

---

README.md

- Removed Compatibility Flags, they're enabled by default now.
- Reword Local testing => Local development?
- ~Looks like it's not necessary to use `experimental-edge` flag with NextJS 13 with default Pages setup. Still required with App directory though.~ Match router example with official NextJS docs.
Edit: Nah I'm getting this msg with it. Reverted.
Edit2: Difference between `experimental-edge` and `edge` is asked [here](https://github.com/vercel/next.js/discussions/44871#discussioncomment-4683660)
```
error - Page /src/pages/api/hello provided runtime 'edge', the edge runtime for rendering is currently experimental. Use 
runtime 'experimental-edge' instead.
```
- Mention NodeJS 18 is not supported.

doc: update readme, cleanup

---

.changeset/seven-cougars-fly.md
README.md
src/index.ts
templates/_worker.js/index.ts

To test:
- `npx create-next-app@latest next-app`
- Opt in to using the `app/` dir
- Add `export const config = { runtime: "edge" };` to `app/api/hello/route.ts` and `export const config = { runtime: "experimental-edge" };` to `app/page.tsx`
- `npx https://prerelease-registry.devprod.cloudflare.dev/next-on-pages/runs/4451651690/npm-package-next-on-pages-115`
- `npx wrangler@latest pages dev .vercel/output/static --compatibility-flag=nodejs_compat`

Add globalThis.AsyncLocalStorage for 13.X versions of Next.js

---

.github/workflows/beta-release.yml

Minor, just to distinguish the workflow on github:

rename beta-release workflow

---

.changeset/short-kiwis-train.md
src/buildApplication/buildApplication.ts
src/buildApplication/buildVercelOutput.ts

Vercel and Next.js generate *private* files for telemetry purposes that are accessible as static assets.
`.vercel/output/static/_next/__private/trace` includes a full output of all info accrued. It also has full path names, which may pose security concerns if accessible (depending on where you are building).
While the new routing system *should* prevent these files from being accessible (if they have a record in the outputted config), they would still be accessible if someone modified an `_routes.json` file to exclude them from invocations.
We do not need these files, nor do we want to run the risk of them being available. Therefore, we should purge them instead of letting them be uploaded to Cloudflare Pages.

feat: remove private/telemetry files from the build output

---

.changeset/famous-ravens-pump.md
src/buildApplication/buildMetadataFiles.ts
src/cli.ts
src/index.ts
src/utils/index.ts
src/utils/version.ts

Adding the next-on-pages version to the CLI messages, I think it's going to be convenient for two reasons:
- if we switch between different versions for example for testing things this can help double checking what the current version is
- when people open issues and provide the CLI output the version might get included which would be helpful
Results:

add next-on-pages version to CLI

---

docs/supported.md

Update the supported doc to reflect:
- no support for `crons` in the build output config
- possible future support for `i18n` in `next.config.js`.

chore: update supported config properties

---

package-lock.json
package.json
vitest.config.ts

The default `edge-runtime` vitest environment appears to not fully support `ArrayBuffer` - https://github.com/vitest-dev/vitest/issues/2884. This causes issues when trying to use `new Response(...)`.
Specifically, it results in `TypeError: Cannot read properties of undefined (reading 'isView')` when trying to construct a new response.
This PR changes the environment we use to Miniflare (`vitest-environment-miniflare`).
An alternate POV is that since we're building for Cloudflare Workers, it might make more sense to use the Miniflare vitest environment as well.

fix: use miniflare for vitest due to edge runtime environment bug

---

.changeset/nine-bikes-poke.md
package-lock.json
package.json
src/buildApplication/buildApplication.ts
src/buildApplication/buildVercelOutput.ts
src/buildApplication/buildWorkerFile.ts
src/buildApplication/generateFunctionsMap.ts
src/buildApplication/generateGlobalJs.ts
src/buildApplication/getCurrentPackageManager.ts
src/buildApplication/nextJsConfigs/getBasePath.ts
src/cli.ts

@dario-piotrowicz
Refactored logger: This is the main change of this pull request, where the logger has been refactored. The blockPrefix flag has been added, which makes all block messages the same.
Added flag: --no-color, -nc: A new flag has been added to disable colored output.
Investigated solutions to separate log instances: There were some investigations made to separate log instances, and one possible solution was added to make it easier. Another possible solution was to add information about the previous log statement, and add an extra \n if it is different, but it was not considered appropriate.
ink: This one is interesting. Was looking on this only after refactoring, If it is small app, I dont think it is nice to use. But I might be wrong.
Im not sure where exactly should I add …

Improve cli logs style

---

.changeset/smart-cows-joke.md
src/cli.ts

Currently, if an unknown argument is passed to the cli, an error is shown with the ZodError message. This error is not user-friendly. The ZodError message should be replaced with a clear and concise message that informs the user that the argument they have passed is not recognized, and show the help menu for valid arguments. 
This will improve the user experience and make it easier for users to work with the cli.
**Current message:** 
```
/Users/tarun/Documents/Personal/open-src/next-on-pages/dist/index.js:735
throw result.error;
^
ZodError: [
{
"code": "unrecognized_keys",
"keys": [
"--hel"
],
"path": [],
"message": "Unrecognized key(s) in object: '--hel'"
}
]
at Object.get error [as error] (/Users/tarun/Documents/Personal/open-src/next-on-pages/dist/index.js:637:23)
at ZodEffects.parse …
```

show a user-friendly error message on unknown cli flag

---

src/buildApplication/generateFunctionsMap.ts

I have seen a number of the following:
Introduced by https://github.com/cloudflare/next-on-pages/pull/173 (sorry my bad 😓)
I'm pretty sure this uncaught exception is caused because we don't away the `rm`, I didn't await it because I don't think it is necessary to wait for the directory to get deleted, but I am adding it back since we need it to avoid this uncaught exception (alternatively I could use `validateDir` here but between that adding the `await` I think that the latter is just simpler/cleaner (also `validateDir` would need to be awaited too))
___
PS: since this is fixing an issue not yet released I think I don't need to create a changeset (this will just be part of #173's changeset)

add missing await for staticStaticDir removal

---

.changeset/modern-candles-shave.md
src/index.ts

I'm using a D1 DB locally at `.wrangler\state\d1\DB.sqlite3`, and running `next-on-pages --watch`
When a function writes to the DB, the sqlite file is modified and triggers a rebuild
I can't think of any valid reason to have .wrangler under the watch paths - I've tested locally and this fixes it

Ignore '.wrangler' directory in watch mode

---

.changeset/orange-colts-fly.md
src/buildApplication/buildApplication.ts
src/buildApplication/buildWorkerFile.ts
src/buildApplication/fixPrerenderedRoutes.ts
src/buildApplication/generateFunctionsMap.ts
src/buildApplication/processVercelOutput.ts
src/utils/fs.ts
tests/src/buildApplication/generateFunctionsMap.test.ts
tests/src/buildApplication/processVercelOutput.test.ts
tests/src/utils/fs.test.ts
vercel.types.d.ts

This PR does the following before processing a directory for functions:
- Checks for any prerendered route configs.
- Checks if prerendered routes already exist in the static assets directory.
- Copies prerendered routes to the static assets directory.
- Returns a filtered list of paths to process that excludes the valid prerendered routes.
- Applies overrides to the build output for prerendered routes, like what would normally happen with static pages in the build output config.
- Adds tests for the new behaviour.

fix: copy static prerendered routes to the static directory

---

.changeset/unlucky-chicken-join.md
templates/_worker.js/routes-matcher.ts
tests/templates/handleRequest.test.ts
tests/templates/requestTestData/index.ts
tests/templates/requestTestData/infiniteLoop.ts

- Introduces a counter for keeping track of how many times the `checkPhase` function is called for each run of the route matcher.
- Returns a 500 error after the counter exceeds 50 loops - this indicates infinite looping.
- Changes the `check: true` behaviour for the `miss` phase.
- If the path is not in the build output, it enters the `filesystem` phase as the `none` phase may cause infinite loops with i18n.
- If a path is in the build output, it resets the status code if it was previously set to 404, and continues with routing like normal.
- Unintentionally introduces basic i18n support.
With i18n, there is a rule in the `none` phase that maps a request from `/*` to `/{default-locale}/*`. At the same time, there is a rule in the `miss` phase to map requests …

fix: prevent infinite loops during routing edge case

---

.changeset/six-squids-tickle.md
docs/supported.md
templates/_worker.js/routes-matcher.ts
templates/_worker.js/utils/http.ts
tests/templates/handleRequest.test.ts
tests/templates/requestTestData/basicEdgeAppDir.ts
tests/templates/requestTestData/i18n.ts
tests/templates/requestTestData/index.ts
tests/templates/requestTestData/middleware.ts
tests/templates/utils/http.test.ts

- Fixes an issue where redirects weren't breaking out of routing at the right point.
- Adds a utility function for parsing the `accept-language` header value.
- Introduces support for the source route `locale` option and the `next.config.js` option for `i18n`.
- Adds tests for the new functionality.
It is somewhat of a continuation of https://github.com/cloudflare/next-on-pages/pull/222 as that fixed a major blocker for i18n.
So, there is a little quirk with how the locale redirects have to be handled. There are two different types of ways internationalization works. These are sub-path routing and domain routing. The build output config `route.src` value for sub-path routing is simply `/`, which causes issues.
The Next.js …

feat: i18n locale redirects support

---

.changeset/hot-eagles-love.md
src/buildApplication/buildWorkerFile.ts
src/buildApplication/generateGlobalJs.ts
src/utils/getNodeEnv.ts
templates/_worker.js/index.ts
tests/src/buildApplication/generateGlobalJs.test.ts
tests/templates/utils/getNodeEnv.test.ts

Commit to AsyncLocalStorage

---

src/buildApplication/buildWorkerFile.ts
src/buildApplication/generateFunctionsMap.ts
tests/src/buildApplication/generateFunctionsMap.test.ts
tests/templates/handleRequest.test.ts

PS: not including any changeset here since this PR is fixing an issue introduced in the same release (so I think that it's actually part of the other changeset)

properly build functions and chunks (so that they can have requires from 'node:buffer'

---

.changeset/tricky-turtles-drum.md
src/buildApplication/fixPrerenderedRoutes.ts
tests/_helpers/index.ts
tests/src/buildApplication/generateFunctionsMap.test.ts

Basically #238 but for prerendered JSON for pages in `_next/data/...`.

fix: prerendered json handling

---

README.md
package-lock.json
package.json
src/buildApplication/buildVercelOutput.ts
tests/_helpers/index.ts

This PR makes Pages CI build using the new v2 beta image work.
The issue is that the current Vercel CLI opens too many file handlers at once (which the v2 beta image doesn't seem to be handling correctly) when building a Next.js >= v.13.3.0 app that contains prerendered routes.
The prerendered routes are problematic because as part of the building process Vercel generates lambda functions for them, such lambda functions include node modules, the parallel downloading of such node modules causes too many files to be open at once.
This PR introduces as a temporary fix the use of a fork of the Vercel CLI that sequentializes the above mentioned problematic downloads solving the issue (see https://github.com/dario-piotrowicz/vercel/commit/4f6355174fbe9717d8b85c0bec9329b7a0d3de60). 
This is …

use vercel fork

---

.changeset/rich-shirts-shake.md
templates/_worker.js/routes-matcher.ts
tests/_helpers/index.ts
tests/templates/handleRequest.test.ts
tests/templates/requestTestData/index.ts
tests/templates/requestTestData/trailingSlash.ts

- In the `rewrite` phase, if no path is found in the build output, check if there is a trailing slash. If so, remove it and check the build output again.
- Adds tests for the new functionality.
When using `trailingSlash: true` in `next.config.js`, it redirects requests to include a trailing slash. However, it doesn't always rewrite the paths in the build output config to let them match. For dynamic routes, there are rewrites present in the `rewrite` phase that account for the trailing slash. However, with non-dynamic routes, there typically isn't a rewrite to take care of them. So, if we weren't able to match a rewrite and there's a trailing slash, we should manually remove it and check if the file system contains the route.
Tested using the reproduction in …

fix: non-dynamic trailing slash matching when using `trailingSlash`

---

.changeset/lucky-toys-confess.md
src/buildApplication/generateFunctionsMap.ts

Blocked by #267 (but otherwise ready for reviewing)
___
Tested on this [api route](https://github.com/dario-piotrowicz/next-apps-for-testing/blob/a04ac505a506a38f0de5263f80637ea5dfc75cd9/apps/simple-pages-dir-13.4.2/pages/api/hello.js) see: https://a9b4b021.next-on-pages-test-5h3.pages.dev/api/hello
resolves #249
___
As mentioned in the changeset not all node built-in modules are supported but that's because of vercel/next itself so there isn't much we can do about it, I'll look into this and open an issue in their repo to allow such imports (but anyways the changes here will work untouched if/when they allow such imports)

fix built-in node modules static imports

---

.changeset/tender-rats-smash.md
src/buildApplication/buildVercelOutput.ts
src/buildApplication/packageManagerUtils.ts
src/cli.ts

fix the getPackageVersion (currently not correctly parsing packages using pnpm) and use it in the getVercelBuildChildProcess to decide if for yarn and pnpm we should include the dlx option
resolves #250
resolves #262
<details>
<summary>Manual testing results</summary>
next-on-pages info:
next-on-pages run with and without ""vercel"" cli, adds `dlx` when expected
___
next-on-pages info:
next-on-pages run with and without ""vercel"" cli (in any case `npx` works well)
___
next-on-pages info:
next-on-pages run with and without ""vercel"" cli, adds `dlx` when expected
</details>

fix getPackageVersion and use it to discern use of dlx

---

.changeset/grumpy-seas-search.md
src/buildApplication/processVercelOutput.ts

- Removes any copied rsc function files (`.rsc.func.js`) from the worker output directory (we do not use them during routing due to them being the same as non-rsc funcs)
- Filters the static assets list that we provide to the routing system to remove the contents of the `_worker.js` directory (this should never have happened in the first place).
This change is primarily to reduce the bundle size by removing files that we don't utilize.
The tiny app that I tested it with had 1 rsc function. The zipped (`tar -zcvf`) sizes were as follows:
- Before: 192451
- After: 179682
- Change: -12769
On my modified version of the [app dir playground](https://github.com/james-elicx/app-playground), the difference is very noticeable:
- Before: 1298780
- After: 858230
- Change: …

fix: avoid copying rsc funcs to output dir

---

.changeset/smooth-pumpkins-press.md
templates/_worker.js/routes-matcher.ts
tests/templates/requestTestData/basicEdgeAppDir.ts

- Alter the regex for the special handling of rewriting `^/` to `/index` to check that the index path is at the start of the pathname.
- Adds a test for the bug fix.
We previously added special handling for the build output config rule rewriting `^/` to `/index` when the `rsc` header is present as it was causing requests to `/non-index-path` to be rewritten. The handling involved verifying that the previous path before the rewrite was actually an index path. However, the regex wasn't checking that it started with the index path, only that one existed in the path, i.e. `*/` or `*/index`.
This meant that it would also match requests with a trailing slash by accident (e.g. `/non-index-path/`, so this change alters the regex to ensure that it is matching at the …

fix: non-index pages with trailing slash rewriting to `/index` for rsc requests

---

.changeset/serious-cobras-run.md
templates/_worker.js/handleRequest.ts
templates/_worker.js/routes-matcher.ts
templates/_worker.js/utils/routing.ts
tests/_helpers/index.ts
tests/templates/requestTestData/middleware.ts

- Modifies the middleware handling to check for the `x-middleware-next` header and act as follows:
- If the header exists, remove it and continue as normal.
- If the header does not exist, and there was no rewrite or location header, this means the middleware response should be the final response we return to the client.
- Therefore, update the final response body and status.
- Changes the middleware error check to only be for status 500 which is what occurs when an error is thrown in a middleware func.
- Checks if a response body was set during middleware processing and if so, bails out of routing and also uses it when returning a response to the client.
- Adds a test for the new logic.
fixes https://github.com/cloudflare/next-on-pages/issues/283

fix: middleware not returning response with `new NextResponse`

---

README.md
package.json

- __converts all relative urls in the README to be absolute urls since relative urls in the npm site result in 404s__
alternatively for fixing the above we could include the `doc` folder in the package as well, but that would increase the package side and number of files... so I'd imagine using absolute urls is preferred? 🤷\
another alternative would be to have a standard gh readme and an npm readme, I think that it wouldn't be too bad having a minimalistic README on npm, but it would require some extra login in the packaging process\
(Please let me know if you prefer one of the other alternatives I'd be equally fine with all of them)
- __Adds missing fields in the package.json related to info displayed on npm__
___
For reference see the current npm next-on-pages page here: …

Apply minor npm improvements

---

.changeset/young-beers-buy.md
src/utils/routing.ts
tests/src/utils/routing.test.ts

- Fixes the regex used to strip route groups to not strip route intercepts.
- Adds a test for the bug fix.
Intercept routes use the format `/(.)path` which was being accidentally caught in the route group stripping, since route groups use `/(name)`. This PR changes that behaviour to exclude brackets that contain periods from matching the route group regex.
fixes #310

fix: intercept routes being unintentionally stripped

---

.changeset/itchy-rings-behave.md
docs/supported.md
templates/_worker.js/handleRequest.ts
templates/_worker.js/routes-matcher.ts
tests/templates/requestTestData/i18n.ts

- Introduces support for the [`wildcard`](https://vercel.com/docs/build-output-api/v3/configuration#wildcard) option in the Vercel build output config.
- Applies wildcard matches to the route destination.
- Adds a test for the new functionality.
- Removes the `prevMatch` optional input for the `RoutesMatcher` constructor since it is never used.

feat: wildcard option support in the build output config

---

.changeset/empty-toys-notice.md
src/index.ts

When using yarn (classic) as the package manager the build process ends up in an infinite loop when using watch mode.
`vercel` is added as a dev dependency when using this package manager. This results in the change in the package.json.
___
resolves #308

Mitigate build loop in watch mode when using yarn (classic)

---

.changeset/four-clouds-travel.md
templates/_worker.js/routes-matcher.ts
templates/_worker.js/utils/routing.ts
tests/templates/requestTestData/i18n.ts

- Introduces yet another hack for i18n to make it work properly.
- Ensures that requests to i18n index routes (e.g. `/nl`) can be rewritten to `/` in the `miss` phase by modifying the relevant source route's regex.
- Adds a test for the bug fix.
As we know from before, the build output config is rather iffy when it comes to `next.config.js` internationalization. The support for it appears to be half-baked. This PR adds another hack to resolve another regex issue for i18n in the build output config. At the moment, our support for statically generated index routes works fine, however, it appears that there is an issue when you use an SSR'd index route that generates an edge function.
In the `miss` phase, there is a source route as follows that is designed to …

fix: i18n locale index request not matching for ssr'd index route

---

.changeset/spicy-pears-boil.md
packages/next-on-pages/templates/_worker.js/routes-matcher.ts
packages/next-on-pages/tests/_helpers/index.ts
packages/next-on-pages/tests/templates/handleRequest.test.ts
packages/next-on-pages/tests/templates/requestTestData/middleware.ts

- Introduces an array to track which middleware has been invoked during each run of a phase.
- If a middleware is tried to be invoked more than once, it skips.
- Adds a test.
In the build output config, there are sometimes two records created for middleware in the `none` phase, both of which can be hit and then accidentally lead to multiple invocations. This PR introduces an array that tracks which middleware paths have been invoked when running a phase. If it tries to use one that has already been invoked, it will skip doing so, fixing the issue of multiple invocations.

fix: middleware being invoked more than once in a phase

---

.changeset/hungry-pianos-serve.md
.changeset/large-pillows-try.md
packages/next-on-pages/templates/_worker.js/handleRequest.ts
packages/next-on-pages/templates/_worker.js/routes-matcher.ts
packages/next-on-pages/templates/_worker.js/utils/routing.ts
packages/next-on-pages/tests/templates/requestTestData/middleware.ts

- Stops applying the search parameters to the `location` header if it is from a middleware.
This appears to be how it behaves in `next dev` for middleware, so I'm happy for this logic to be removed.
fixes #335

fix: middleware redirects accidentally applying search params

---

.changeset/pretty-icons-impress.md
packages/eslint-plugin-next-on-pages/src/rules/no-unsupported-configs.ts
packages/eslint-plugin-next-on-pages/tests/rules/no-unsupported-configs.test.ts

updating the eslint `no-unsupported-configs` rule based on the supported table updated in https://github.com/cloudflare/next-on-pages/pull/319

update configs in no-unsupported-configs eslint rule

---

.changeset/rude-hotels-raise.md
packages/next-on-pages/templates/_worker.js/routes-matcher.ts
packages/next-on-pages/tests/_helpers/index.ts
packages/next-on-pages/tests/templates/requestTestData/middleware.ts

- Ensures we bail out of routing when a middleware response is present
Previously, we added a fix to bail out of routing when running a middleware returned a response. However, this change didn't account for when the request was to a route that doesn't exist in the build output. This fix ensures that it always bails out when a user returns `new NextResponse`, regardless of if the target route is in the build output. This is the correct behaviour that should have happened before 🙈
fixes #341

fix: middleware returns 404 with `new NextResponse` on invalid route

---

packages/eslint-plugin-next-on-pages/src/rules/missing-image-loader.ts
packages/eslint-plugin-next-on-pages/src/rules/no-nodejs-runtime.ts
packages/eslint-plugin-next-on-pages/src/rules/no-unsupported-configs.ts
packages/next-on-pages/src/buildApplication/generateFunctionsMap.ts

@petebacondarwin I'm removing the `try`-`catch` `assert`s pattern I've been following
I've spent a bunch of time trying to think of how to not use `assert`s in a nice way but I've been struggling to find something I'd be happy with.
If I were to define many small/granular utility functions for AST nodes that would likely produce lots of functions which would just add lots of noise and wouldn't simply things too much (they would just make checks more readable).
If I were to define more chunky/specific utility functions they likely just one used once again, potentially adding noise without too much benefit, they would need to be alongside smaller `if`s which (could use or not more granular utility functions).
Chunky utility functions would also not provide great type safety and we'd be …

Remove asserts from production code

---

.changeset/few-garlics-shout.md
packages/next-on-pages/src/buildApplication/generateFunctionsMap.ts

<details>
<summary>Results on a very small app</summary>
Before
After
This doesn't seem to make a huge difference on small applications but I believe that the duplication of the manifest data in large applications can spin out of control
</details>
<details>
<summary>Results on a medium/small app</summary>
Before
After
Here I think we do start seeing how much this can impact the overall app size 😄 
</details>
<details>
<summary>Results on a large app</summary>
After checking with the creator of #330 it seems like their application went from over 25MB to 9.8MB 🙂
Before
After
I was hoping that the size of the app would reduce even further but this is still quite a sizeable improvement 🙂 
</details>
____
resolves #330

deduplicate Next.js manifests

---

.changeset/wicked-radios-yawn.md
packages/next-on-pages/src/buildApplication/generateFunctionsMap.ts

Result on [app-playground-edge](https://github.com/dario-piotrowicz/next-apps-for-testing/tree/master/apps/app-playground-edge):
<p align="center">
| Before | After |
|--------|--------|
| ![Screenshot 2023-06-29 at 13 22 01](https://github.com/cloudflare/next-on-pages/assets/61631103/614246f1-6350-4dd0-8cf0-a10562b2ebc1) | ![Screenshot 2023-06-29 at 13 24 36](https://github.com/cloudflare/next-on-pages/assets/61631103/6d947373-60ff-42df-8391-4b7f07e7066c)
</p>
Not a huge saving in size but the the reduction of files needed could be important for large applications (I think it can potentially solve https://github.com/cloudflare/workers-sdk/issues/3391)

Avoid "deduping" webpack chunks used by a single function

---

packages/next-on-pages/src/buildApplication/generateFunctionsMap.ts

This is a temporary fix and should be resolved ASAP in a refactor of how the logic for processing the output works.
These two fixes are for errors thrown when using the `--skip-build` mode when deduplication has already taken place before.
Chunk deduping error that is fixed:
Manifest deduping error that is fixed:

temp fix for chunk + manifest deduping in `--skip-build`

---

packages/next-on-pages/templates/_worker.js/index.ts
packages/next-on-pages/templates/_worker.js/utils/images.ts
packages/next-on-pages/tests/templates/utils/images.test.ts

This PR fixes a weird issue where every other refresh in the browser would not show the image.
The actual fix is making the response mutable and applying the headers to it, instead of creating a new response with the new headers from the resp body. Why? I don't know - I assume something on the response object being weird. Don't ask me why this fixes it, but it does.
Oh, and this PR also includes an unrelated change to fetch relative assets in the build output through the assets fetcher instead of a fetch request.
and the other thing this pr does is also respect the expected cache-control response header behaviour of falling back to the minimumcachettl config value
https://e572d143.image-resizing-test.pages.dev/

fix: image resizing returning weird response

---

.changeset/neat-terms-boil.md
packages/next-on-pages/templates/_worker.js/utils/http.ts
packages/next-on-pages/tests/templates/utils/http.test.ts

- Changes the `applySearchParams` function to append on unique key-value combos, instead of overriding them.
- Ensures that internal Next.js search params from matches in the build output config always override so routes function properly.
From what I understand, this is common behaviour and is how it should have been implemented originally.

fix: query params not appending with the same key

---

.changeset/clean-experts-tap.md
packages/next-on-pages/src/buildApplication/generateFunctionsMap.ts
packages/next-on-pages/src/buildApplication/generateGlobalJs.ts
packages/next-on-pages/templates/_worker.js/index.ts
packages/next-on-pages/templates/_worker.js/utils/fetch.ts
packages/next-on-pages/templates/_worker.js/utils/index.ts
packages/next-on-pages/tests/src/buildApplication/generateGlobalJs.test.ts

This PR allows us to handle vercel asset fetches such as the one present in this example: https://vercel.com/docs/concepts/functions/edge-functions/og-image-generation/og-image-examples#using-a-custom-font
Which makes it possible to use `@vercel/og` 🚀 😄 
Result:
[simple-wasm-pages-13.3.1](https://github.com/dario-piotrowicz/next-apps-for-testing/tree/master/apps/simple-wasm-pages-13.3.1) deployed at: https://a9aeda25.next-on-pages-test-5h3.pages.dev
resolves #39

improve bundled assets handling

---

.changeset/seven-socks-roll.md
packages/next-on-pages/templates/_worker.js/routes-matcher.ts
packages/next-on-pages/tests/templates/requestTestData/middleware.ts

- Ensures we always bail out of routing when a middleware returns a redirect.
- Adds a test.
Previously, it was still possible for the routing to find a match in a later entry in the build output config. In the case of RSC requests, this would lead to overriding the found headers from the middleware because of the override rule on RSC matching entries in the build output config, discarding the redirect header from the middleware. This PR changes it so that when we encounter a redirect in a middleware, we bail out of routing straight away, instead of proceeding through the stages.
This is probably what should have been done originally, to be honest.
This resolves an issue that was raised in the Cloudflare Discord with Clerk.

fix: middleware redirect not always bailing out of routing

---

.changeset/tame-goats-perform.md
packages/next-on-pages/templates/_worker.js/index.ts
packages/next-on-pages/templates/_worker.js/utils/fetch.ts

Example of what this PR fixed:
Fetch to the GitHub REST API:
[source code](https://github.com/dario-piotrowicz/next-apps-for-testing/blob/master/apps/simple-app-dir-13.4.2/app/api/gh-nop/route.ts)
| Before | After |
|--------|--------|
| ![Screenshot 2023-07-18 at 16 39 54](https://github.com/cloudflare/next-on-pages/assets/61631103/c0344943-6772-48e8-838d-1920033bff5a) | ![Screenshot 2023-07-18 at 16 38 54](https://github.com/cloudflare/next-on-pages/assets/61631103/915312b4-81ef-45ea-a842-cb0055c31723) | 
| <sup><sub>https://a3caa9a5.next-apps-for-testing.pages.dev/api/gh-nop/</sub></sup>|<sup><sub>https://2bdb5dc5.next-apps-for-testing.pages.dev/api/gh-nop/</sub></sup>|

refactor fetch patching and add missing user-agent header setting

---

.changeset/gorgeous-carrots-breathe.md
packages/next-on-pages/templates/_worker.js/handleRequest.ts
packages/next-on-pages/templates/_worker.js/routes-matcher.ts
packages/next-on-pages/tests/_helpers/index.ts
packages/next-on-pages/tests/templates/handleRequest.test.ts
packages/next-on-pages/tests/templates/requestTestData/configRewritesRedirectsHeaders.ts

- Fixes an issue where full-URL rewrites were actually redirecting instead of rewriting the URL.
- Fixes the relevant test.
Previously, when a path was rewritten to an URL and it didn't set a `location` header, we set one for it. This was incorrect and it should not have done this. Instead, we should have treated that as the new rewritten destination and sent a fetch request to *proxy* the request to the URL. The response from fetching the rewritten URL should then be used as the response to be returned to the client.
Note that I am currently using Jacob (on Pages team)'s site for the tests, but I am happy to change the URL if you wish.

fix: `next.config.js` URL rewrites unintentionally redirecting instead of rewriting

---

.changeset/tough-ghosts-boil.md
packages/next-on-pages/src/buildApplication/buildApplication.ts
packages/next-on-pages/src/buildApplication/buildMetadataFiles.ts

- Grabs the `{...}/_next/static` path from the static assets instead of always using `/_next/static` for the `_routes.json` file.
This allows the `/_next/static` assets to be excluded from worker invocations when in a subdirectory, instead of always assuming they are at the root.
Fixes #396

fix: `/_next/static` in subdir not excluded from routing

---

.github/workflows/beta-release.yml
.github/workflows/configs-docs-scraping.yml
.github/workflows/create-pullrequest-prerelease.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml
.gitignore
package.json
turbo.json

resolves #367 
| Before | with npm caching | with npm and turbo caching<br/>(with all full turbo) |
|--------|--------|-------|
| [![Screenshot 2023-07-05 at 13 51 11](https://github.com/cloudflare/next-on-pages/assets/61631103/4045da67-b169-4ef2-8866-22c200dc28c4)](https://github.com/cloudflare/next-on-pages/actions/runs/5456442488) | [![Screenshot 2023-07-05 at 13 53 12](https://github.com/cloudflare/next-on-pages/assets/61631103/c7e7cbf4-9a4c-4f93-b636-68a4a6e6bc8c)](https://github.com/cloudflare/next-on-pages/actions/runs/5464461977) | [![Screenshot 2023-07-05 at 18 04 23](https://github.com/cloudflare/next-on-pages/assets/61631103/26755f84-f3eb-4a67-8890-40c38f79037f)](https://github.com/cloudflare/next-on-pages/actions/runs/5466966647) |
Notes:
- The Turbo caching doesn't seem to …

add caching to github workflows

---

.changeset/khaki-parrots-visit.md
packages/next-on-pages/src/buildApplication/buildSummary.ts
packages/next-on-pages/src/buildApplication/processVercelFunctions/ast.ts
packages/next-on-pages/src/buildApplication/processVercelFunctions/dedupeEdgeFunctions.ts
packages/next-on-pages/tests/src/buildApplication/buildSummary.test.ts

- Groups code block identifiers by their consumers.
This drastically reduces the number of unique files created for things like Webpack chunks by grouping them into the same file when they are consumed by the same function, which was causing issues in certain projects.
Fixes [#3391](https://github.com/cloudflare/workers-sdk/issues/3391) (right?)

feat: group identifiers by their consumers

---

.changeset/green-lemons-shop.md
packages/next-on-pages/src/buildApplication/buildMetadataFiles.ts

- Copies the entries from an `_routes.json` file found in the root directory to our generated version.

feat: support for `_routes.json` in the root dir

---

.changeset/polite-ways-matter.md
packages/next-on-pages/env.d.ts
packages/next-on-pages/src/buildApplication/buildApplication.ts
packages/next-on-pages/src/buildApplication/buildVercelOutput.ts
packages/next-on-pages/src/buildApplication/packageManagerUtils.ts
packages/next-on-pages/src/cli.ts
packages/next-on-pages/tests/src/buildApplication/packageManagerUtils.test.ts

- Introduces support for using Bun as a package manager in projects.
- Refactors some of the package manager utilities (sorry, I couldn't help myself).
- Fixes pnpm always using `dlx` instead of `exec` when `vercel` is installed as a dev dependency.
- Updates the relevant tests.
Manual Testing Locally:
<details>
<summary>* yarn</summary>
Tested manually with yarn 1:
I don't think you can test prereleases with yarn berry so I'm asking that
</details>

feat: Bun as a package manager support

---

.changeset/fifty-radios-rhyme.md
packages/next-on-pages/src/buildApplication/processVercelFunctions/build.ts
packages/next-on-pages/src/buildApplication/processVercelFunctions/dedupeEdgeFunctions.ts

- Normalizes the import paths that get injected on Windows machines.
This should hopefully resolve the following issue that I believe is caused by backslashes in Windows path names:
```
[X [ERROR] Could not resolve "......__next-on-pages-dist__webpackee2d6a0d46f7afe4402d9e841f4a3be3.js"
<stdin>:1:124:
1 │ ...838 } from '..\..\..\__next-on-pages-dist__\webpack\ee2d6a0d46f7...
╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
You can mark the path "......__next-on-pages-dist__webpackee2d6a0d46f7afe4402d9e841f4a3be3.js" as external to exclude it from the bundle, which will remove this error.
```

fix: normalize injected import paths on windows

---

.changeset/wet-laws-wink.md
packages/next-on-pages/src/index.ts

fixes #400 
> **Note**
> By debugging an application using yarn (to solve #400) I noticed that the `public` directory was continuously getting detected as being added, I am not sure why that is but I don't think there is any benefit for us in watching directories addition/removals and the like, so I am simply changing the watch function to only trigger the re-build on file changes (which I'd assume are the only events we should care about)

watch mode only on file changes

---

.changeset/sweet-grapes-dance.md
package-lock.json
packages/next-on-pages/package.json

[vercel@32](https://github.com/vercel/vercel/releases/tag/vercel%4032.0.0) has been released.
The only major change is that the Node.js minimum has been raised, so adding it to peer dependencies should not be a problem.

Add vercel@32 as a peer dependency

---

packages/next-on-pages/package.json
packages/next-on-pages/templates/_worker.js/routes-matcher.ts

The next-on-pages lint script was wrongfully not including the templates directory so I am adding it so that we correctly get lints checks there

include templates in next-on-pages lint script

---

.changeset/five-rules-call.md
packages/next-on-pages/src/buildApplication/generateGlobalJs.ts

- Allows `process.env` to be enumerated over.
This enables things like `Object.entries(process.env)` to work when it's a proxy.

fix: `process.env` not enumerable due to being a proxy

---

.changeset/orange-swans-peel.md
packages/next-on-pages/src/buildApplication/buildWorkerFile.ts

- Normalizes the injected entrypoint for Windows platforms.
This fixes an issue where the function entrypoint we inject breaks as it might use double backslashes on Windows because, well, Windows has to ruin everything.
```
"/api/hello":{type:"function",entrypoint:"__next-on-pages-dist__\functionsapihello.func.js"}
```

fix: broken function entrypoints on windows

---

.changeset/old-sheep-visit.md
packages/next-on-pages/templates/_worker.js/utils/pcre.ts
packages/next-on-pages/tests/templates/utils/pcre.test.ts

- Accounts for underscores when applying PCRE matches.
NOTE: Vercel does not include the underscore in the [code](https://github.com/vercel/vercel/blob/0a08e4b/packages/cli/src/util/dev/router.ts#L16) that I used as a reference when originally writing this. I am sceptical as to whether we should proceed with this, but as it works in `next dev`, I imagine we should go ahead with it.
fixes https://github.com/cloudflare/next-on-pages/issues/453

fix: dynamic params with underscore not applying correctly

---

.changeset/famous-dragons-joke.md
packages/next-on-pages/templates/_worker.js/routes-matcher.ts
packages/next-on-pages/templates/_worker.js/utils/matcher.ts
packages/next-on-pages/templates/_worker.js/utils/pcre.ts
packages/next-on-pages/tests/templates/utils/matcher.test.ts
packages/next-on-pages/tests/templates/utils/pcre.test.ts

- Changes the logic to use the PCRE match function for `has` entries as the regex is expected to be in the PCRE format.
- For PCRE matches in the `has` entries, attempts to update the route's destination with any named capture groups extracted.
Relevant docs: https://nextjs.org/docs/app/api-reference/next-config-js/rewrites#header-cookie-and-query-matching
fixes #448

fix: named captures in `has` fields not applying to route dest

---

.changeset/rich-squids-visit.md
packages/next-on-pages/src/buildApplication/buildApplication.ts
packages/next-on-pages/src/buildApplication/processVercelFunctions/configs.ts
packages/next-on-pages/src/buildApplication/processVercelFunctions/edgeFunctions.ts
packages/next-on-pages/src/buildApplication/processVercelFunctions/index.ts
packages/next-on-pages/src/buildApplication/processVercelFunctions/invalidFunctions.ts
packages/next-on-pages/tests/_helpers/index.ts
packages/next-on-pages/tests/src/buildApplication/processVercelFunctions/invalidFunctions.test.ts
packages/next-on-pages/tests/src/buildApplication/processVercelFunctions/prerenderFunctions.test.ts

- Checks the build output config for i18n keys.
- Ignores invalid functions that match those i18n keys and have a valid alternative function.
- Adds a reason to the ignored function entries in the nop-build-log file.
- Adds a few tests for the fix.
fixes #464 which is caused by Vercel CLI version >= 32.2.0

fix: ignore invalid i18n functions with valid alternatives

---

packages/next-on-pages/src/buildApplication/getVercelConfig.ts
packages/next-on-pages/templates/_worker.js/routes-matcher.ts
packages/next-on-pages/templates/_worker.js/utils/routing.ts
packages/next-on-pages/tests/src/buildApplication/getVercelConfig.test.ts
packages/next-on-pages/tests/src/buildApplication/processVercelOutput.test.ts
pages-e2e/features/appRouting/500.test.ts

issue #470 happens because Vercel generated route srcs don't contain appropriate `$` at the end, if can be fixed by adding ad-hoc `$` as we've done in the past, I am however trying to see, can we just always add `$`? is that how Vercel interprets such regexes anyways?

add $ to all route srcs

---

.changeset/wild-olives-invent.md
packages/next-on-pages/src/buildApplication/processVercelFunctions/dedupeEdgeFunctions.ts

when dealing with wasms that have more than 1 consumer, when we collect the wasm imports to prepend for a specific edge funcion we're always re-setting the array of wasm imports instead of appending them, this causes edge functions to always only consider the last wasm import, fix such issue
resolves #494

fix wasmImportsToPrepend overriding existing imports

---

.changeset/quiet-roses-design.md
packages/next-on-pages/templates/_worker.js/utils/request.ts

This pull request aims to fix the small incompatibility between real Vercel and the simulated Vercel headers by replacing headers, instead of appending to their values. This should fix #507

Replace append with set in adjustRequestForVercel (Fixes #507)

---

.changeset/great-geckos-brake.md
.changeset/silent-walls-remain.md
.changeset/ten-feet-thank.md
.changeset/wise-jeans-lay.md
packages/next-on-pages/src/buildApplication/processVercelFunctions/invalidFunctions.ts
packages/next-on-pages/src/buildApplication/processVercelFunctions/prerenderFunctions.ts
packages/next-on-pages/src/utils/routing.ts
packages/next-on-pages/templates/_worker.js/utils/http.ts
packages/next-on-pages/tests/src/buildApplication/processVercelFunctions/invalidFunctions.test.ts
packages/next-on-pages/tests/src/buildApplication/processVercelFunctions/prerenderFunctions.test.ts

This PR fixes the following issues relating to the `next.config.js` `basePath` option:
- infinite redirect for prerendered base path root.
- base path root index.rsc not generating a non-index rsc override.
- _not-found function hack not working with base paths.
- not discard an invalid unnecessary base path function at the root with a valid alternative.
fixes #516

fix: several issues with `next.config.js` `basePath` option

---

.changeset/eighty-spoons-decide.md
packages/next-on-pages/src/buildApplication/processVercelFunctions/dedupeEdgeFunctions.ts

https://github.com/vercel/next.js/pull/57815 introduced a critical bug for us that breaks rendering due to the assumption that their internal request shape is always `NodeNextRequest` (and should have the `originalRequest` property on it), and is never `WebNextRequest` (which doesn't have the `originalRequest` property).
This fix is intended to be a temporary band-aid until the issue is fixed in Next.js. I raised an issue at https://github.com/vercel/next.js/issues/58265.

temp-fix: rendering error in next.js 14.0.2 caused by next.js bug

---

.changeset/twenty-eggs-lick.md
packages/next-on-pages/templates/_worker.js/index.ts

fixes https://github.com/cloudflare/next-on-pages/issues/535
Honestly, this one kind of confuses me a bit, but from what I can tell, patching the fetch in the global scope results in it interacting with the static generation store from the previously run function.
You can see in the below screenshot that for some reason part way through running the function, it skips from the index.func.js to the other.func.js, even though there are no references in either file to use the webpack chunks inlined in the other (i am using disable-chunks-dedup here).
And my console.logs in each function file also indicate that it bizarrely jumps between executing code in one another.
<details>
<summary>index.func.js</summary>
</details>
<details>
<summary>other.func.js</summary>
</details>
So it really is …

fix: patch fetch in the fetch handler instead of global scope

---

.changeset/neat-deers-work.md
.changeset/rare-rings-own.md
packages/eslint-plugin-next-on-pages/src/index.ts
packages/eslint-plugin-next-on-pages/src/rules/no-app-not-found-runtime.ts
packages/eslint-plugin-next-on-pages/tests/rules/no-app-not-found-runtime.test.ts

Fixes #530 
fixes #531
I put them in the same PR to avoid conflicts when merging since I also added a test file that both of them use.

Fixes for ESLint rule no-app-not-found-runtime

---

.changeset/sixty-wolves-type.md
packages/next-on-pages/templates/_worker.js/routes-matcher.ts

- Fixes the logic for rewriting rsc requests so that it correctly handles `/__index.prefetch.rsc` -- it was previously rewriting those requests to `/__index` which resulted in a 404.
- Stops stripping the `.prefetch.rsc` suffix as these are correctly stripped by Vercel at a later phase in the build output config.
fixes #542

fix: broken rewrites for __index.prefetch.rsc

---

.changeset/brown-insects-protect.md
packages/next-on-pages/templates/_worker.js/utils/request.ts

Older versions of Next.js only use the `x-vercel-sc-host` request header and not the `SUSPENSE_CACHE_URL` env variable, therefore set the request header.

fix: set `x-vercel-sc-host` for older versions of Next.js

---

.changeset/twelve-cobras-double.md
packages/next-on-pages/docs/caching.md
packages/next-on-pages/env.d.ts
packages/next-on-pages/src/buildApplication/buildApplication.ts
packages/next-on-pages/src/buildApplication/buildWorkerFile.ts
packages/next-on-pages/templates/_worker.js/utils/cache.ts
packages/next-on-pages/templates/cache/adaptor.ts
packages/next-on-pages/templates/cache/cache-api.ts
packages/next-on-pages/templates/cache/kv.ts

- Builds the cache templates to the nop dist dir (and fixes the import extension in them since we're not bundling the adaptor code).
- Changes to lazy import internal cache adaptors.
- Adds KV cache adaptor.
- Automatically uses KV cache adaptor when the `KV_SUSPENSE_CACHE` binding is present.
- Updates docs.
Cache API demo: https://next-cache-demo.pages.dev/
KV binding demo: https://kv.next-cache-demo.pages.dev/
partially solves https://github.com/cloudflare/next-on-pages/issues/529

feat: kv binding support for suspense cache

---

.changeset/wicked-shoes-crash.md
packages/next-on-pages/src/buildApplication/processVercelFunctions/dedupeEdgeFunctions.ts

Apparently, the variable can be `$` which wasn't getting hit by the regex.

fix: match more chars for the next.js bug fix

---

.changeset/empty-cups-pull.md
packages/next-on-pages/templates/_worker.js/utils/cache.ts
packages/next-on-pages/templates/cache/adaptor.ts

- Updated `CachedFetchValue` type introduced in Next.js 13.5.
- When retrieving cache tags, falling back to `x-vercel-cache-tags` header if cache tags are not given from fetched `CachedFetchValue` object.
fixes #556

fix: Falling back to header if cache tags are not given from fetched object

---

.changeset/good-squids-join.md
.changeset/shaggy-wombats-happen.md
packages/next-on-pages/templates/_worker.js/utils/cache.ts
packages/next-on-pages/templates/cache/adaptor.ts

- Fixes old Next.js versions not updating cache entry properly because they didn't receive the tags how they expected. Sorry, this is my fault since I suggested to delete that property.
- Adds some support for soft/implicit tags that were introduced by https://github.com/vercel/next.js/pull/53321.
Fwiw, I think there might still be some more work potentially to improve support for newer versions of the suspense cache, but this PR should bring us to a good spot.
I did actually notice that Next.js deciding when it needs to update a stale entry was more reliable on older Next.js versions before they made these changes over the past few months, but that would be something that might need looking into separately, but I don't think there's anything we can really do …

some support for suspense cache soft/implicit tags

---

.changeset/pretty-buttons-join.md
packages/next-on-pages/src/buildApplication/getVercelConfig.ts
packages/next-on-pages/src/buildApplication/processVercelFunctions/invalidFunctions.ts

resolves #528 
___
This PR implements the `isUsingAppRouter` which can then be used to tackle #413 automatically for the user without asking them to manually ignore invalid routes (as suggested in #497)

Try to fix not_found routes only when the app router is used

---

pages-e2e/features/appRouting/ssr-dynamic.test.ts
pages-e2e/features/appRoutingSsrDynamicCatchAll/assets/app/ssr-dynamic-catch-all/catch-all/[...pets]/page.js
pages-e2e/features/appRoutingSsrDynamicCatchAll/assets/app/ssr-dynamic-catch-all/optional-catch-all/[[...colors]]/page.jsx
pages-e2e/features/appRoutingSsrDynamicCatchAll/main.feature
pages-e2e/features/appRoutingSsrDynamicCatchAll/setup.ts
pages-e2e/features/appRoutingSsrDynamicCatchAll/ssr-dynamic-catch-all.test.ts
pages-e2e/features/pagesRouting/ssr-dynamic.test.ts
pages-e2e/features/pagesRoutingSsrDynamicCatchAll/assets/pages/ssr-dynamic-catch-all/catch-all/[...pets].jsx
pages-e2e/features/pagesRoutingSsrDynamicCatchAll/assets/pages/ssr-dynamic-catch-all/optional-catch-all/[[...colors]].jsx
pages-e2e/features/pagesRoutingSsrDynamicCatchAll/main.feature
pages-e2e/features/pagesRoutingSsrDynamicCatchAll/setup.ts
pages-e2e/features/pagesRoutingSsrDynamicCatchAll/ssr-dynamic-catch-all.test.ts
pages-e2e/fixtures/appLatest/main.fixture
pages-e2e/fixtures/pagesLatest/main.fixture

The e2es were checking for a incorrect rendering of slugs for catch-all routes, that seems to have been fixed upstream by Next making the `appLatest` and `pagesLatest` e2es failing.
So this PR changes the e2es so that we check for the correct rendering of slugs now, but only for the latest fixtures (the older fixtures do not check for the incorrect rendering anymore as that would overcomplicate the `(app|pages)Routing` features and is also actually not too useful of a check).
> PS: So we can sometimes get lucky and get fixes (and not only new bugs) from upstream! 🤯 😄 🥳

Update failing e2es (in regards to slugs rendering)

---

internal-packages/docs-scraper/scripts/createOrUpdateIssue.ts

The github markdown for warning has changed: https://github.com/orgs/community/discussions/16925
Causing the warning markdown not to be displayed as intended (see: https://github.com/cloudflare/next-on-pages/issues/463):
The changes here just update the markdown so that it shows the warning properly:

Update warning syntax in docs-scraper message

---

.changeset/orange-buttons-add.md
.changeset/witty-kids-repair.md
internal-packages/next-dev/package.json
internal-packages/next-dev/src/durableObjects.ts
package-lock.json
packages/next-on-pages/package.json

Hey! 👋 Tried to debug #621 this afternoon. I think PR this should fix things. I'm still a bit confused why this issue was only exposed with new Miniflare versions, but this seems to be working for me locally.
The issue was that `createClass()` was being called with a class name like `<workerName>_<className>` as opposed to just `<className>`. This meant in the target `wrangler dev` session containing the Durable Object, we were trying to `env["<workerName>_<className>"]` instead of `env["<className>"]` resulting in the `Cannot read properties of undefined` error.
___
resolves #621

Fix Durable Object bindings proxy with new Miniflare versions

---

.changeset/polite-rice-grab.md
internal-packages/next-dev/src/utils.ts

Very minor change, I just noticed that the warnings in `setupDevBindings` could use a small indentation
| Before | After |
|--------|--------|
| ![Screenshot 2024-01-17 at 16 26 56](https://github.com/cloudflare/next-on-pages/assets/61631103/fb339230-baeb-4552-8687-751ab91c8df1) | ![Screenshot 2024-01-17 at 16 24 59](https://github.com/cloudflare/next-on-pages/assets/61631103/ff036aa0-b77e-46cd-8f28-70adfe1c3fc2) | 
> [!NOTE]
> I've applied the same indentation in the D1 warning in #642

indent `setupDevBindings` warnings

---

.changeset/neat-rockets-perform.md
internal-packages/next-dev/src/index.ts

I just noticed that providing an `options` object without a `bindings` field results in a terminal error:
The error is not really very clear so instead of it here I am simply adding assertions and throwing more clear errors for users:
> [!NOTE]
> Throwing makes the error show up in the console but does not kill the nodejs process, I don't think I can kill the dev server process from within `setupDevBindings`

add assertions for making sure that the required `setupDevBindings` options are provided

---

packages/next-on-pages/README.md
packages/next-on-pages/src/api/getRequestContext.ts

Applying some changes to `getRequestContext` based on feedback received here: https://github.com/cloudflare/next-on-pages/discussions/596#discussioncomment-8443400
___
> [!NOTE]
> no changeset is needed since `getRequestContext` hasn't yet been released

address `getRequestContext` feedback

---

.changeset/beige-ducks-glow.md
packages/next-on-pages/src/api/getRequestContext.ts

This PR adds information in the `getRequestContext`'s error message (but only during local development) reminding the user to setup the dev platform via `setupDevPlatform` in their config file
As suggested here: https://github.com/cloudflare/next-on-pages/pull/659#issuecomment-1950260006

Make the `getRequestContext`'s error message more helpful during local development

---

.changeset/fresh-years-tap.md
packages/next-on-pages/src/buildApplication/processVercelFunctions/dedupeEdgeFunctions.ts
packages/next-on-pages/src/buildApplication/processVercelFunctions/edgeFunctions.ts
packages/next-on-pages/vercel.types.d.ts

- Introduces some support for the `filePathMap` option in a function config file.
- Symlinks assets to the function's folder, so that they can be found during the build process.
fixes #676
fixes #672
Example of this in a function's `.vc-config.json`:

fix: bundled wasm assets not found during build

---

.changeset/funny-berries-beg.md
packages/next-on-pages/templates/_worker.js/routes-matcher.ts

Partially fixes #665 (it fixes the `404` results described in the issue)
> [!NOTE]
> It would be great to add an e2e test for this, but due to time constraints on my part and the fact that this issue is quite edge case (and also relies on the Pages router being used, which is not recommended), I'm thinking not to add such e2e

fix `trailingSlash` set to `true` alongside `i18n` enabled causing incorrect `404`s

---

.changeset/proud-coats-raise.md
internal-packages/next-dev/src/shared.ts

This PR fixes the fact that `process.env` doesn't contain the proper bindings during dev mode
You can see a reproduction of the issue here: https://github.com/dario-piotrowicz/next-on-pages-local-process.env-issue-repro
This is a regression introduced in https://github.com/cloudflare/next-on-pages/pull/659
There I removed the `bindingsProxyHasBeenSetSymbol` flag used to see if `process.env` was properly patched and just relied on the existence of `runtimeContext[cloudflareRequestContextSymbol]` instead.
Unfortunately this doesn't work since Next.js itself creates/updates the `process.env` object thus we cannot/should not use external flags to see if it was patched but the flag has to be part of the `process.env` object itself. So that if Next.js has replaced the object we can see that and …

fix `process.env` not giving access to bindings during local development (in `next-dev`)

---

.changeset/fuzzy-turkeys-try.md
packages/eslint-plugin-next-on-pages/docs/rules/no-app-nodejs-dynamic-ssg.md
packages/eslint-plugin-next-on-pages/src/index.ts
packages/eslint-plugin-next-on-pages/src/rules/no-app-nodejs-dynamic-ssg.ts
packages/eslint-plugin-next-on-pages/src/utils/ast-traversal.ts
packages/eslint-plugin-next-on-pages/tests/rules/no-app-nodejs-dynamic-ssg.test.ts
packages/eslint-plugin-next-on-pages/tests/utils/ast-traversal.test.ts

this PR adds the new `no-app-nodejs-dynamic-ssg` eslint rule that makes sure that developers using `generateStaticParams` also export either the `runtime` variable set to `edge` or the `dynamicParams` one set to `false`

add new `no-app-nodejs-dynamic-ssg` eslint rule

---

internal-packages/next-on-pages-tsconfig/tsconfig.json

fix the shared tsconfig file in the next-on-pages-tsconfig internal package by adding a missing outDir value to its compilerOptions
___
without the `outDir` the `tsconfig.json` files extending the shared one provide this error/warning:
I think this happens because, if no `outDir` is provided typescript assumes that that current directory is also where the files are going to be saved, does any `.js`/`.mjs` files there could produce an infinite loop

fix shared tsconfig file

---

.changeset/shaggy-colts-rhyme.md
packages/next-on-pages/src/api/getRequestContext.ts

Throw a user friendly error message when `getRequestContext` is called during prerendering

---

.changeset/lazy-avocados-swim.md
packages/next-on-pages/templates/_worker.js/utils/images.ts

The Next.js server doesn't pass the request headers when fetching external images but fetches using solely the image's url  ([source](https://github.com/vercel/next.js/blob/39340ab42428606685be8bf8a01b080f385c3eb1/packages/next/src/server/next-server.ts#L585))
We're instead passing the original request headers as well, which generates security risks, this PR addressed such issue
Thanks a lot @gabrielf to bringing this to my attention 🙂🙏

make sure that the original request headers are not passed along when fetching external images

---

.changeset/loud-owls-remember.md
packages/next-on-pages/src/index.ts

fix: runBuild should exit with 1 on unexpected errors (when watch mode is disabled)

---

.changeset/slimy-toys-lie.md
.changeset/swift-garlics-flash.md
internal-packages/next-dev/src/index.ts
packages/next-on-pages/package.json

- fixes the `setupDevPlatform`'s options parameter not being optional
- updates `package.json` to properly export the typescript types
[discord discussion about the types being broken with pnpm](https://discord.com/channels/595317990191398933/1222961811528089632)

Improve/fix `next-dev` types support

---

.changeset/fast-points-count.md
packages/next-on-pages/templates/_worker.js/utils/cache.ts
packages/next-on-pages/templates/cache/adaptor.ts

Parallelizes operations while loading the cache tags manifest, and locally caches them for up to a second to avoid refresh on each cache request. On cache update, uses `ctx.waitUntil` instead of blocking the response while update is in progress.
I don't have real-life test numbers, but on our website where some pages require a 3 API request waterfall to render, I easily was seeing 400ms "wasted" by writing data to the cache. These changes solved my issue.

Cache loading and update optimization

---

.changeset/purple-rocks-pump.md
packages/next-on-pages/templates/cache/adaptor.ts
packages/next-on-pages/templates/cache/cache-api.ts
packages/next-on-pages/templates/cache/kv.ts

fixes https://github.com/cloudflare/next-on-pages/issues/757
This PR sets the expiry parameters of the next suspense cache based on the revalidation parameter.
[The aim of this PR is to support revalidation tags of the kind](https://nextjs.org/docs/app/building-your-application/data-fetching/fetching-caching-and-revalidating#time-based-revalidation):
```
await fetch('/path', {
next: {
revalidate: 900,
}
);
```
In K-V, this is implemented as `expirationTtl`, in cache api as the cache control `max-age` header.
The `revalidate` parameter needs to be optional to support setting tags in the adaptor - will this work with the tags manifest operations at the same time?

Add expiry to suspense cache based on revalidate

---

.changeset/hot-socks-beg.md
packages/next-on-pages/templates/_worker.js/routes-matcher.ts

Suggested fix for issue [#808 ](https://github.com/cloudflare/next-on-pages/issues/808) where middleware redirect status not saving which leads to 307 redirect.
fixes #808

Middleware move permanently fix

---

.changeset/quiet-glasses-buy.md
packages/next-on-pages/src/buildApplication/processVercelFunctions/configs.ts
packages/next-on-pages/src/utils/fs.ts
packages/next-on-pages/tests/src/utils/fs.test.ts

fixes #825
new vercel cli release changed the vc-config type for favicon.ico to `API`, so added a check for if an `API` function has a prerendered config existing...
(rolling eyes)

support prerendered api functions

---

.changeset/warm-rivers-reply.md
packages/next-on-pages/src/buildApplication/processVercelFunctions/configs.ts
packages/next-on-pages/src/buildApplication/processVercelFunctions/invalidFunctions.ts
packages/next-on-pages/src/buildApplication/processVercelFunctions/prerenderFunctions.ts
packages/next-on-pages/src/utils/fs.ts
packages/next-on-pages/tests/_helpers/index.ts
packages/next-on-pages/tests/src/buildApplication/processVercelFunctions/invalidFunctions.test.ts
packages/next-on-pages/tests/src/buildApplication/processVercelFunctions/prerenderFunctions.test.ts

new vercel cli update no longer generates prerender configs for dynamic ISR functions when it generates valid children for the route.
this pr does the following:
- checks if invalid func is a dynamic isr function
- if it is, it checks if there is prerendered function for the dynamic routes sourcepath
- if there are, it marks the dynamic function as ignored.
fixes #833
source path in prerender config for reference:

Fix prerendered dynamic ISR functions change in Vercel CLI

---

.changeset/curly-weeks-sin.md
packages/next-on-pages/templates/_worker.js/utils/request.ts

Fix #839 
~~Just like what @marcojakob observed on city names in #788, we should also encode region and country names for the location of the requester's public IP address.~~
`request.cf.region` is the full name of the region the user is in, however according to the doc, [x-vercel-ip-country-region](https://vercel.com/docs/edge-network/headers#x-vercel-ip-country-region) should be an [ISO 3166-2](https://en.wikipedia.org/wiki/ISO_3166-2) code, and I believe `request.cf.regionCode` is the correct value to be used here.
So that problems like what I met:
```
✘ [ERROR] Problematic header name or value: "Västra Götaland County" (raw bytes: "\x56\xe4\x73\x74\x72\x61\x20\x47\xf6\x74\x61\x6c\x61\x6e\x64\x20\x43\x6f\x75\x6e\x74\x79"). This string contains 8-bit characters in the range 0x80 - 0xFF. …
```

Fix `x-vercel-ip-country-region` header's value

---

.changeset/thirty-birds-build.md
packages/next-on-pages/src/buildApplication/processVercelFunctions/dedupeEdgeFunctions.ts
packages/next-on-pages/templates/_worker.js/index.ts
packages/next-on-pages/templates/_worker.js/routesIsolation.ts
pages-e2e/features/_utils/getAssertVisible.ts
pages-e2e/features/customEntrypoint/assets/custom-entrypoint.ts
pages-e2e/fixtures/app14.0.0/main.fixture

currently routes all share the same global scope, this can be problematic and cause race conditions and failures, like the one presented in #805 that happens when various requests are handled in parallel (and the global scope ends up in an invalid state).
So, this PR solves the issue by wrapping each js file (functions and chunks included) in functions that override the `self`, `globalThis` and `global` symbols with proxies that try to make (as reasonably well as possible) each route's global scope as isolated as possible.
____
fixes #805

implement route scoping solution

---

packages/next-on-pages/src/buildApplication/processVercelFunctions/dedupeEdgeFunctions.ts

The `iifefyFunctionFile` function introduced in https://github.com/cloudflare/next-on-pages/pull/836 incorrectly modified `_ENTRIES` when they are actually declared in the function file (they should be modified only when they are global references), this PR fixes such issue
> [!NOTE]
> This PR does not include a changeset since the changes in https://github.com/cloudflare/next-on-pages/pull/836 have not yet been released and this PR simply improves that solution

avoid tweaking `_ENTRIES` if an `_ENTRIES` declaration is present

---

.changeset/odd-lemons-jog.md
packages/next-on-pages/src/buildApplication/processVercelFunctions/invalidFunctions.ts

This expands on the change in #834 to fix prerendered routes with catch-all (e.g. blog/[...slug]/page.tsx -> blog/foo and blog/category/bar) routes.
I ran into an issue trying to get [timlrx/tailwind-nextjs-starter-blog](https://github.com/timlrx/tailwind-nextjs-starter-blog) working on Cloudflare Pages. For the most part, everything worked, but for blog posts in particular, there were two issues: first, somewhere in the stack code is `eval`-ed, so posts cannot be rendered on the edge runtime and must be prerendered. The second: next-on-pages wasn't doing whatever magic it usually does for a typical blog/[slog]/page.tsx, so I was getting an error telling me to add `runtime = 'edge'`.
This change applies the same fix to `[...param]` routes as it does `[param]` routes. I readily admit, I am …

Fix prerendered dynamic ISR functions with catch-all segments

---

.changeset/real-wolves-destroy.md
packages/next-on-pages/src/buildApplication/processVercelFunctions/build.ts

Tested locally in a repo where we encountered the bug (caused by https://github.com/vercel/next.js/pull/65426) and as far as I can tell this should be backwards compatible / pretty safe.
~~I'm not 100% sure this is the right approach but it is an easy fix at least.~~ I now actually think this is a neat way to fix it.
Fixes #876.

Define process.env.__NEXT_BUILD_ID in edge functions to be Next 14.2.8+ compatible

---

.changeset/nasty-kids-tickle.md
packages/next-on-pages/src/buildApplication/processVercelFunctions/ast.ts

When using sentry, you get a SequenceExpression with the CallExpression inside it. We need to find that CallExpression so we can use it for deduping.
fixes #860

fix: webpack chunks not deduping with sentry

---

.changeset/stupid-dragons-brake.md
packages/next-on-pages/src/buildApplication/buildWorkerFile.ts
packages/next-on-pages/src/buildApplication/processVercelFunctions/build.ts

fixes #908
Latest Vercel dependency broke the build because they didn't use the node prefix so we weren't accounting for it.

fix: mark `async_hooks` as external

---

.changeset/sweet-chairs-explode.md
packages/next-on-pages/src/buildApplication/buildWorkerFile.ts

This PR fixes an issue where when using a custom entrypoint, it's not possible to import `node:` or `cloudflare:` packages.

Allow import of node:* and cloudflare:* in worker custom entrypoint

---

.changeset/bright-vans-relate.md
packages/next-on-pages/src/buildApplication/processVercelFunctions/dedupeEdgeFunctions.ts

fix Next.js calling a non-bound waitUntil method

---

.changeset/modern-spoons-speak.md
packages/next-on-pages/templates/_worker.js/utils/cache.ts
packages/next-on-pages/templates/_worker.js/utils/fetch.ts

Newer versions of esbuild try to resolve dynamic imports by [crawling the filesystem for matching modules](https://esbuild.github.io/api/#glob). This doesn't work with the code `next-on-pages` generates, because the modules don't necessarily exist on the filesystem.
This PR extracts a `moduleName` variable so that esbuild doesn't try to look for matching modules on the filesystem.

Extract module name

---

.changeset/nervous-balloons-rule.md
packages/next-on-pages/templates/_worker.js/utils/cache.ts
packages/next-on-pages/templates/_worker.js/utils/doImport.ts
packages/next-on-pages/templates/_worker.js/utils/fetch.ts

Take 2 of https://github.com/cloudflare/next-on-pages/pull/940, which was still inlining dynamic imports due to esbuild's minification algorithm removing the intermediate variables.

_Really_ don't inline dynamic imports

---

.changeset/dull-ads-rush.md
packages/next-on-pages/package.json

As title—allow Wrangler v4 in peer deps in prep for release

Allow Wrangler v4

---

.changeset/healthy-beans-heal.md
.changeset/rich-dogs-push.md
packages/next-on-pages/templates/_worker.js/index.ts

resolves https://github.com/cloudflare/next-on-pages/issues/956

Make sure next-on-pages can work with Next 15.2
