src/index.ts

It's called `next-on-pages`, not `next-to-pages`.

---

templates/_worker.js/index.ts

adjust request so that it contains geo headers

---

.changeset/wise-camels-sleep.md
src/index.ts
src/utils/index.ts
src/utils/transform/index.ts
src/utils/transform/manifest.ts
tests/manifest.test.ts

- Created a new utility function for matching manifest function entries with the file paths we obtain.
- Support route handlers.
- Added tests for the utility function.
fixes #105

feat: support route handlers

---

.github/workflows/beta-release.yml

Oops, accidentally copy-pasted a line specific to wrangler

Fix beta releases

---

package.json

add prepare script so that package can be installed through git

---

.changeset/gentle-melons-turn.md
src/buildApplication/buildWorkerFile.ts
src/buildApplication/generateGlobalJs.ts
templates/_worker.js/globals.js
tests/src/buildApplication/generateGlobalJs.test.ts

allow setting of NODE_ENV

---

.changeset/healthy-zebras-knock.md
src/buildApplication/buildApplication.ts
src/buildApplication/buildWorkerFile.ts

fixing a stupid mistake I made :facepalm:

fix experimental minification always on

---

.github/ISSUE_TEMPLATE/bug-report.yml
.github/ISSUE_TEMPLATE/feature-request.yml
docs/contributing.md

To check out the result see: https://github.com/dario-piotrowicz/nextjs-app-dir-test/issues/new/choose

add issue templates

---

.changeset/modern-keys-mix.md
.changeset/silly-tips-sparkle.md
src/buildApplication/buildApplication.ts

add an error when buildOutput fails

---

.changeset/clever-queens-cough.md
src/buildApplication/buildApplication.ts

properly align invalid functions in error message

---

.changeset/swift-islands-doubt.md
src/buildApplication/buildWorkerFile.ts

fix require-call typo in nodeBufferPlugin

---

.changeset/friendly-poets-smile.md
README.md
src/buildApplication/buildApplication.ts
src/buildApplication/buildWorkerFile.ts
src/buildApplication/generateFunctionsMap.ts
src/cli.ts
src/index.ts
tests/src/buildApplication/generateFunctionsMap.test.ts

replace experimental-minification with chunks-deduplication

---

.changeset/strong-llamas-protect.md
src/buildApplication/buildApplication.ts

fix: Failed Vercel build doesn't produce a non-zero result

---

.changeset/slow-suits-deliver.md
package.json
src/buildApplication/buildWorkerFile.ts
src/buildApplication/generateFunctionsMap.ts

This change should be ready to go after the following wrangler change is released: https://github.com/cloudflare/workers-sdk/pull/2966
resolves #54

implement lazy loading via Pages' _worker.js directory

---

src/buildApplication/generateFunctionsMap.ts

currently in the Cloudflare runtime imports to node built-in modules inside nested directories don't correctly resolve, so fix this by creating a non-nested node-buffer file and importing node:buffer from that.
IMPORTANT: this fix is temporary and should be reverted
as soon as the runtime bug has been fixed
(which should be soon)

add temporary workaround for runtime node:buffer bug

---

docs/supported.md

I'm pretty sure env variables work as expected, as you can see if you try running this app: https://github.com/dario-piotrowicz/next-apps-for-testing/blob/43f55d6b7e1538e5b8cb16221a3fea53896c8239/apps/simple-app-dir-13.3.1/next.config.js#L7

update documented support for env variables

---

.changeset/chilly-fireants-fold.md
src/buildApplication/generateFunctionsMap.ts

Added "node:events" to external config for the functionsmap generation. #244

---

README.md

I'm adding the info in a way consistent with what @james-elicx did here: https://github.com/cloudflare/cloudflare-docs/pull/8939

add requirement to install next-on-pages to README

---

.changeset/flat-bobcats-glow.md
src/buildApplication/generateFunctionsMap.ts
tests/templates/handleRequest.test.ts

Tested with [simple-wasm-pages-13.3.1](https://github.com/dario-piotrowicz/next-apps-for-testing/tree/master/apps/simple-wasm-pages-13.3.1): https://4ace7296.next-on-pages-test-5h3.pages.dev/
resolves #202

Add wasm support

---

.changeset/small-bears-work.md
src/buildApplication/generateFunctionsMap.ts
src/buildApplication/generateGlobalJs.ts

I think that the runtime bugs have been fixed, I've tried building an app with the changes in this PR and all seems to be working fine now.
[app](https://github.com/dario-piotrowicz/next-apps-for-testing/tree/master/apps/simple-app-dir-13.3.1): https://52951c30.next-on-pages-test-5h3.pages.dev

remove runtime hacks

---

src/buildApplication/generateFunctionsMap.ts

fix wasm replacement breaking when multiple wasm modules are present

---

.changeset/breezy-ducks-knock.md
.changeset/pink-actors-learn.md
internal-packages/eslint-config-next-on-pages/index.js
packages/next-on-pages/src/buildApplication/buildVercelOutput.ts
packages/next-on-pages/src/cli.ts
packages/next-on-pages/src/index.ts
packages/next-on-pages/src/utils/fs.ts

add missing `await`s for `getPackageVersion` calls

---

internal-packages/eslint-config-next-on-pages/index.js
internal-packages/eslint-config-next-on-pages/package.json
package-lock.json
packages/eslint-plugin-next-on-pages/package.json
packages/eslint-plugin-next-on-pages/src/rules/missing-image-loader.ts
packages/eslint-plugin-next-on-pages/src/rules/no-unsupported-configs.ts
packages/next-on-pages/package.json

as part of this also clean up related packages dependencies and add an eslint rule to warn about deprecated calls
___
@petebacondarwin followup for https://github.com/cloudflare/next-on-pages/pull/343#discussion_r1244023677 🙂👍

bump eslint packages and remove deprecated calls

---

.github/workflows/pull-request.yml
package.json

add pretest:e2e script to make sure that we always have a built next-on-pages package before running the e2e tests

 add pretest:e2e script

---

.github/actions/cache-turbo/action.yml
.github/actions/node-setup/action.yaml
.github/workflows/beta-release.yml
.github/workflows/configs-docs-scraping.yml
.github/workflows/create-pullrequest-prerelease.yml
.github/workflows/pull-request.yml
.github/workflows/release.yml

You can see in this PR's [PR checks run](https://github.com/cloudflare/next-on-pages/actions/runs/5659385010) that the workflow still works as expected 🙂
(the other workflows will need to be tested after merging 😓)

use local composite actions to reduce yml code duplication

---

.changeset/proud-lamps-tie.md
packages/next-on-pages/src/buildApplication/packageManagerUtils.ts

adjust package version detection in yarn

---

.changeset/empty-tools-occur.md
packages/next-on-pages/src/buildApplication/getVercelConfig.ts
packages/next-on-pages/templates/_worker.js/routes-matcher.ts

correctly handle newly introduced .prefetch.rsc suffixes

---

.changeset/hungry-poets-melt.md

PR #473 has been merged without a changes so this PR is simply introducing such changeset
resolves #470

add changeset for PR #473

---

packages/next-on-pages/docs/static-assets-routing.md
packages/next-on-pages/docs/worker-invocation.md

Probably worth documenting this feature.

docs: information about opting assets out of routing

---

.changeset/spotty-buckets-fry.md
packages/eslint-plugin-next-on-pages/src/rules/no-unsupported-configs.ts
packages/eslint-plugin-next-on-pages/tests/rules/no-unsupported-configs.test.ts

Add support for extension .mjs in no-unsupported-configs rule

---

.changeset/fast-masks-attack.md
packages/next-on-pages/src/index.ts

Improve run build error message

---

.changeset/blue-seals-fail.md
packages/next-on-pages/src/buildApplication/buildApplication.ts

print warning in case developers are using a different package manager to run @cloudflare/next-on-pages

---

.changeset/olive-needles-lay.md
packages/next-on-pages/templates/_worker.js/routes-matcher.ts

Properly handle external middleware rewrites

---

.changeset/tender-suns-agree.md

in #585 I forgot to add a changeset, so I am adding it here 🤦

add missing changeset for #585

---

packages/next-on-pages/docs/supported.md

Just a super small fix to the caching documentation link.

Fix broken link

---

.changeset/silver-kings-attend.md
internal-packages/next-dev/README.md
internal-packages/next-dev/package.json
internal-packages/next-dev/src/durableObjects.ts
internal-packages/next-dev/src/index.ts
package-lock.json
packages/next-on-pages/package.json

Example/Demo of this new API's usage: https://github.com/dario-piotrowicz/next-on-pages-stable-next-dev-test-demo
resolves #527 
resolves #271

Stabilize the next-dev API

---

internal-packages/next-dev/README.md

since the change was so small, thought i would just update it, but if this was incorrect, feel free to discard!
[Reference Issue](https://github.com/cloudflare/next-on-pages/issues/626)

chore: update bindings docs 

---

.changeset/healthy-ads-knock.md
packages/next-on-pages/templates/_worker.js/utils/images.ts
packages/next-on-pages/tests/templates/utils/images.test.ts

Thanks a lot @gabrielf for the suggested changes 🙂

make sure protocol relative URLs are not treated as actual relative URLs

---

.changeset/city-header-encoding.md
package-lock.json
packages/next-on-pages/templates/_worker.js/utils/request.ts

Fix city header encoding (RFC3986)

---

README.md
packages/next-on-pages/docs/caching.md

improve the caching documentation and recommend KV as the storage solution

---

packages/next-on-pages/CHANGELOG.md

amend changelog not to show incorrect ctx destructuring

---

.changeset/little-rings-notice.md
packages/next-on-pages/package.json

fix types not getting properly built

---

.github/ISSUE_TEMPLATE/bug-report.yml

Fix bug report template supported features link

---

packages/next-on-pages/README.md

Fixed URL in `packages/next-on-pages/README.md`

Fixed URL in README.md

---

packages/eslint-plugin-next-on-pages/docs/rules/no-app-nodejs-dynamic-ssg.md
packages/eslint-plugin-next-on-pages/docs/rules/no-pages-nodejs-dynamic-ssg.md
packages/next-on-pages/README.md
packages/next-on-pages/docs/supported.md
packages/next-on-pages/src/api/getRequestContext.ts

Fixes broken troubleshooting links in error message and markdown. See: #865 
Closes #865

Fixes broken links to troubleshooting page

---

docs/technical/routing.md

This pull request includes changes to the `docs/technical/routing.md` file to improve the readability and clarity of the flowcharts by using HTML tags for formatting.
Improvements to flowchart readability:
* `docs/technical/routing.md`: Enhanced the flowchart descriptions by replacing newline characters with HTML `<br>` tags and adding bold formatting to key terms. This change makes the flowcharts easier to read and understand.
| Before | After |
|--------|--------|
| <img width="826" alt="Screenshot 2024-11-18 at 3 39 33 PM" src="https://github.com/user-attachments/assets/9c55fca1-f7b8-4f8f-923d-95e25b15367a"> | <img width="826" alt="Screenshot 2024-11-18 at 3 40 05 PM" src="https://github.com/user-attachments/assets/0c985ff6-c1a8-4ef4-a068-21eae337da84"> |
| <img width="1004" …

Improve flowchart readability in routing.md
